#!/usr/bin/env bash
script_dir=$(realpath "$(dirname "${BASH_SOURCE[0]}")")

# Wait for devislpie to start
until pids=$(pidof devilspie2)
do   
    sleep 1
done
sleep 4

function start() {
    lua=$1
    class=$2
    cmd_to_start=$3
    wezterm --config-file ${script_dir}/${lua} start \
        --class ${class} \
        -- ${cmd_to_start} &
}


start wez_widget.lua rg.wezfurlong.wezweather "${script_dir}/get_weather"
start wez_widget.lua rg.wezfurlong.wezres btm
start wez_widget.lua rg.wezfurlong.wezlog  'journalctl -f'

wezterm --config-file  ${script_dir}/wez_widget.lua --config 'font_size=14' start \
    --class rg.wezfurlong.wezclock  \
    -- $(realpath ${script_dir}/../../extras/peaclock) \
           --config=${HOME}/.config/peaclock/peaclock.conf  \
           --config-dir=${HOME}/.config/peaclock &