#!/usr/bin/env bash
mins=30
weather_url='http://wttr.in/Irakleion?QnF&lang=el'

while : 
do
    weather=$(curl --silent $weather_url)
    echo -e "\e[2J"
    printf "%s"  "$weather"
    
    # Pihole stats
    pi_stats=$(curl --silent http://192.168.2.10/admin/api.php)
    dns_queries_today=$(echo $pi_stats | jq .dns_queries_today )
    ads_blocked_today=$(echo $pi_stats | jq .ads_blocked_today )
    ads_percentage_today=$(echo $pi_stats | jq .ads_percentage_today )

    printf "\n\nPi Hole: DNS Queries: %s  Blocked: %s  Ratio: %s%% " "${dns_queries_today}" "${ads_blocked_today}" "${ads_percentage_today:0:5}"

    # Hide the cursor
    echo -e "\e[25l"

    sleep $(( 60 * ${mins} ))
    clear
done