#!/usr/bin/env bash
script_dir=$(realpath "$(dirname "${BASH_SOURCE[0]}")")
cmd_to_start='journalctl -f'

# export SYSTEMD_COLORS=false
function start() {
    wezterm --config-file ${script_dir}/journal.lua start \
        --class rg.wezfurlong.wezlog \
        -- ${cmd_to_start} 
}

# sleep 2
start
xdotool --window gnome-shell mousemove 0 0  click 1 sleep 0.01 mousemove restore