#!/usr/bin/env bash
script_dir=$(realpath "$(dirname "${BASH_SOURCE[0]}")")
cmd_to_start="btm"

# export SYSTEMD_COLORS=false
function start() {
    wezterm --config-file ${script_dir}/resview.lua start \
        --class rg.wezfurlong.wezres \
        -- ${cmd_to_start} 
}


# sleep 2
start
